### ISSUE TITLE
Can't get PCB working with Brutzler software

### ISSUE THREAD

**Issue by jwiggams** [jago85/Brutzelkarte_PCB#2]
Hi jago85,

I can't get this PCB to show any signs that it's working with the Brutzler software. It can see the device COM port but I can't upload the bootloader or anything else to it. I've tried on two different computers as well, just to be safe.

Here's what I've got so far:
- PCB was manufactured and assembled according to your files. All parts and values were pulled from the Kicad design.
- Lattice Diamond compiled with no errors. Using a Lattice programmer the .jed file was successfully written to the PCB.
- Brutzler program was compiled with the latest version of Visual Studio 2019 and appears to work.

All voltages are proper on the PCB, and there are no shorts. I've soldered JP1 on the back so it's the same as the picture you have on the github page...but that didn't make any difference.

Is there something else I need to do to get the software to recognize the cart? How can I test to be sure that it's doing anything at all?

**Comment by jwiggams** [comment]
I've got the cart working with the BRUTZLER program now (had to remove the resistors on the UART lines).

But I'm having issues compiling the bootloader with libdragon - there is an error in the asm code that it won't let me get passed. Do you happen to have a pre-compiled rom for that menu?

**Comment by jago85** [comment]
Hi,
good that you found this. The resistors are only needed if not using the FTDI. But I didn't know, that they prevent the communication when the FTDI is installed.

There are pre-compiled binaries attached to the releases. (Also for the other parts. You shouldn't have to compile anything.)
https://github.com/jago85/Brutzelkarte_Bootloader/releases/download/V0.1.0/brutzelmenu.7z

What exactly is the error message? I'd like to keep the code compatible with libdragon. Maybe this can be fixed.

Btw. JP1 is for the region selection: Closed = NTSC, Open = PAL (if I remember correctly) 

Edit:
Just attached an additional zip file:
https://github.com/jago85/Brutzelkarte_Bootloader/releases/download/V0.1.0/brutzelmenu.zip

**Comment by jwiggams** [comment]
The error may be a Visual Studio Code error, but it's complaining about this line in the asm section:
"unknown register name '$8' C/C++(1118)"

I totally missed the releases, thanks for the tip. OK, so I re-did all my programming with your binaries, but I can't boot the cart on the console. I've tried JP1 both open and closed, and VIO jumper both open and closed, but no difference. The Brutzler software shows everything writing correctly (does it verify after a write?), but when I try to dump the contents with a N64 cart dumper I get no valid data after I've written the bootloader and a ROM...so I don't know what I'm missing.

**Comment by jago85** [comment]
You wrote: "All parts and values were pulled from the Kicad design." So, didn't you use the BOM in the release?
https://github.com/jago85/Brutzelkarte_PCB/releases/download/Rev_1.1/brutzelkarte_bom_r1.1.pdf

Please verify the parts. The KiCad files are not that precise as I used it more as a template and filled the BOM in a separate sheet.

The SPI Flashs often have different options and may not work if they don't match. The VIO jumper also depends on the specific Flash option. The Bootloader Menu should display something without any ROM. So this should be our starting point.

The written data is not verified. Everything is in a really basic state, but there multiple carts in the wild that seem to work pretty stable.

My cart is not ready at the moment as I'm experimenting with a larger Flash chip. But I'll have some time soon to prepare some test commands which can be sent via a terminal like Docklight.

**Comment by jwiggams** [comment]
Everything is the same as the BOM except I substituted U7 for W25Q64JVSSIM, as W25Q64JVSSIQ‎ was out of stock. They seem to be the same chip as far as I can tell, except the one I subbed supports DTR. Would that make it incompatible?

**Comment by jago85** [comment]
In general the chips should be compatible. The M-Version doesn't have the Quad Enable bit fixed to '1'. But this can be set with a command. I have to check if there is a problem with this. Unfortunately I do not have such a chip here. Will try to get my hands on one soon.

**Comment by jago85** [comment]
I've prepared some test commands. I tried with Docklight and HTerm. Are you familiar with one of these terminals?

Connect to your COM port with the settings 3000000 8n1 (3MBaud, 8 data bits, no parity one stop bit). Flow control is off.

All the following data bytes are in hex format.

```
ReadVersion
10 02 09 10 03
Res
10 02 04 00 02 01 10 03

SetAddr (ROM)
10 02 01 00 00 00 00 10 03
Res
<empty>

SetAddr (BOOT)
10 02 01 01 00 00 00 10 03
Res
<empty>

ReadFlash
10 02 04 10 03
Res
10 02 <256 data bytes, 0x10 is doubled> 10 03

EraseFlash
10 02 02 10 03
Res (when ready)
10 02 01 10 03

WriteFlash
10 02 03 <256 data bytes, 0x10 must be doubled> 10 03
Res (when ready)
10 02 01 10 03
```

First test command should be: 
ReadVersion
Send: 
10 02 09 10 03
Receive: 
10 02 04 00 02 01 10 03

Then you can try to read from the flash. First adjust the address and then send a read command. The internal address pointer is automatically increased und the ReadFlash command can be sent repeatedly.

SetAddr (BOOT)
ReadFlash
Receive something like:
10 02 37 80 40 12 00 00 0F 00 <252 more data> 10 03

You will recognize a problem here, I think.

You can also read the ROM flash.
SetAddr (ROM)
ReadFlash

You can also try to erase a flash sector. The Boot Flash has 4 KiB sectors and the ROM flash has 256 KiB sectors. You erase a sector by setting the address to the address of a sector and then apply a EraseFlash command. After erasing a sector the Flash should be returning FF when read back.

SetAddr (BOOT)
EraseFlash
SetAddr (BOOT)
ReadFlash

SetAddr (ROM)
EraseFlash
SetAddr (ROM)
ReadFlash


Hope the explanation is clear. Can you please check the Flash memories with the commands?

I've checked the manual for the W25Q64JV and the code. The Quad Enable bit is set during initialization. But maybe there is a problem and I never realized it because my chip is forced to Quad mode.

I'll prepare a config for the FPGA with a slighly different initialization of the chip for you to test later.

**Comment by jwiggams** [comment]
Sorry for the delay in getting back to you!

I've tried the commands, and am getting results back so the chips are communicating - so that's a good sign! Here is what I get:
ReadVersion
I received this back : 10 02 04 00 02 00 10 03 - it's close but one value is different (due to the variant I assume).

When I try a read from the ROM address space, I get valid data back (it matches the ROM that I wrote). So the flash memory for the ROM data is working properly.

However, when I set the address to BOOT and then try a read, I only get back 0xCC values. Even after doing an erase command I only get 0xCC when I read from it. So apparently this variant is just different enough that it isn't a drop in replacement... 

I've found the exact flash chip you used for the bootrom from a different supplier, and am hoping to get it later this week. I'll drop that in and report back once I have it. I'm sure that will be all that's needed, as the board does appear to be working otherwise.

Thanks for your help so far! I really appreciate it :)

**Comment by jago85** [comment]
No problem, we're not in a hurry.

The ReadVersion command reads the version of the FPGA. It's correct because you have 0.2.0. I confused this with the working branch.

Good, that the ROM Flash is working.

Hm, 0xCC has the bit 3 and bit 2 set for the nibbles. IO3 and IO2 have pull ups. Perhaps this is only the inactive bus state read back.

The FPGA is reading the ID of the Flash, but is not doing anything with it yet. Do you have a scope? You could check if the Flash is sending back something to the first command. This is done over SPI 1x and doesn't need the Quad Mode. I could also implement the ability to read back the ID which could be a useful diagnosis tool anyway.

I'll also get my hands on the M-Version very soon. May be a good alternative part (although I hoped that it would already be compatible).

Here is the promised configuration with the slighly different initialization. But I wouldn't be suprised if this doesn't change anything.
[brutzelkarte_impl1.zip](https://github.com/jago85/Brutzelkarte_PCB/files/5726842/brutzelkarte_impl1.zip)

**Comment by jwiggams** [comment]
The new configuration didn't make a difference, unfortunately. But I can report that I received the W25Q64JVSSIQ‎ chip in and that does work properly! So the cartridge is now working as intended, with the W25Q64JVSSIQ‎ variant.

Should we close this ticket and maybe open a different one for adding support for the W25Q64JVSSIM variant?

**Comment by jago85** [comment]
This is great news. I'm glad that it works now.

I'm curious what the reason is. I'll definitely check this out. Yes, I'll create a new issue.

Stay tuned for new software. I'm working on a version where you can replace single ROMs without having to re-flash the rest. This works even if the memory gets fragmented. But it needs updates to every software and I'm not yet done with the Brutzler tool.

**Comment by jago85** [comment]
Got my W25Q64JVSSIM recently and already found the problem. The chip select is released too short between commands when initializing the chip.
https://github.com/jago85/Brutzelkarte_FPGA/issues/2
